hospital_to_id_map = {
  'brand': 'a03F0000009FQ7V',
  'sbmc': 'a03F0000009Ev1c',
  'mmc': 'a03F0000009EvQQ',
  'CMMC': 'a03F0000009Ev1h',
  'NBI': 'a03F0000009Ev1S',
  'CMC': 'a03F0000009Ev1N',
  'KMC/Monmouth Medical Center, Southern Campus': 'a03F0000009Ev1X',
  'Hospice and Home Car': 'a03F0000009YdRH',
  'JCMC': 'a03F0000009buV7',
  'Rider University': 'a03F000000Ig4aW',
  'Pur Beverage': 'a03F000000If1eU',
  'Morristown Medical Center': 'a03F0000009Ev18',
  'Overlook Medical Center': 'a03F0000009Ev1m',
  'Newton Medical Center': 'a03F000000A9jXI',
  'Chilton Medical Center': 'a03F000000A9jXN',
  'Goryeb Children\'s Hospital': 'a03F000000A9jXS',
  'Atlantic Health Brand': 'a03F000000J29GR',
  'Robert Wood Johnson Brand': 'a03F000000Jm4t0'
}

barnabas_daily_keywords = {
  'BH 08 JCMC': 'a03F0000009buV7',
  'BH 00 EC 005845': None,
  'BH 00 Brand': 'a03F0000009FQ7V',
  'BH 01 SBMC': 'a03F0000009Ev1c',
  'BH 02 MMC': 'a03F0000009EvQQ',
  'BH 03 NBI': 'a03F0000009Ev1S',
  'BH 04 CMMC': None,
  'BH 05 KMC': 'a03F0000009Ev1X',
  'BH 06 CMC': 'a03F0000009Ev1N',
}

media_types = [
  { 'displayOrder': '1',
    'mediaTypeId': '1',
    'mediaTypeName': 'Blogs'},
  { 'displayOrder': '2',
    'mediaTypeId': '2',
    'mediaTypeName': 'Videos'},
  { 'displayOrder': '3',
    'mediaTypeId': '4',
    'mediaTypeName': 'Images'},
  { 'displayOrder': '4',
    'mediaTypeId': '5',
    'mediaTypeName': 'Mainstream News'},
  { 'displayOrder': '5',
    'mediaTypeId': '8',
    'mediaTypeName': 'Twitter'},
  { 'displayOrder': '6',
    'mediaTypeId': '10',
    'mediaTypeName': 'Forums'},
  { 'displayOrder': '7',
    'mediaTypeId': '9',
    'mediaTypeName': 'Forum Replies'},
  { 'displayOrder': '8',
    'mediaTypeId': '11',
    'mediaTypeName': 'Comments'},
  { 'displayOrder': '9',
    'mediaTypeId': '12',
    'mediaTypeName': 'Facebook'},
  { 'displayOrder': '10',
    'mediaTypeId': '13',
    'mediaTypeName': 'Aggregator'},
  { 'displayOrder': '11',
    'mediaTypeId': '14',
    'mediaTypeName': 'Buy/Sell'},
  { 'displayOrder': '13',
    'mediaTypeId': '16',
    'mediaTypeName': 'MySpace'}
]

report_media_type_names = ['Twitter', 'Facebook', 'MySpace', 'Comments', 'Images', 'Videos', 'Forums', 'Forum Replies']
report_media_types = list(filter(lambda mt: mt['mediaTypeName'] in report_media_type_names, media_types))
report_media_type_ids = list(map(lambda mt: mt['mediaTypeId'], report_media_types))

advanced_filter_types = [
  { 'name': 'Classificiation', 'typeId': '7'},
  { 'name': 'Topic Profile Sentiment Subjects', 'typeId': '11'},
  { 'name': 'Engagement Level', 'typeId': '4'},
  { 'name': 'Widget Keywords', 'typeId': '12'},
  { 'name': 'Keyword Group', 'typeId': '9'},
  { 'name': 'Language', 'typeId': '1'},
  { 'name': 'Media Type', 'typeId': '2'},
  { 'name': 'Media Type', 'typeId': '23'},
  { 'name': 'Post Tag', 'typeId': '6'},
  { 'name': 'Region', 'typeId': '0'},
  { 'name': 'Sentiment', 'typeId': '3'},
  { 'name': 'Source Tag', 'typeId': '5'},
  { 'name': 'User Assignment', 'typeId': '8'}
]

count_types = [
  { 'CountType': { 'countTypeId': '0',
                   'label': 'Comment Count',
                   'tooltip': None}},
  { 'CountType': { 'countTypeId': '1', 'label': 'View Count', 'tooltip': None}},
  { 'CountType': { 'countTypeId': '4',
                   'label': 'Likes and Votes',
                   'tooltip': None}},
  { 'CountType': { 'countTypeId': '2',
                   'label': 'Twitter Followers',
                   'tooltip': None}},
  { 'CountType': { 'countTypeId': '3',
                   'label': 'On Topic Inbound Links',
                   'tooltip': None}},
  { 'CountType': { 'countTypeId': '5',
                   'label': 'Total Inbound Links',
                   'tooltip': None}},
  { 'CountType': { 'countTypeId': '6',
                   'label': 'Unique Source Count',
                   'tooltip': None}}
]

region_types = [ { 'isoCountryCode': 'RE',
    'languageId': '0',
    'regionName': 'Reunion',
    'regionTLD': '.re',
    'regionid': '182'},
  { 'isoCountryCode': 'DE',
    'languageId': '4',
    'regionName': 'Germany',
    'regionTLD': '.de',
    'regionid': '82'},
  { 'isoCountryCode': 'AE',
    'languageId': '0',
    'regionName': 'United Arab Emirates',
    'regionTLD': '.ae',
    'regionid': '232'},
  { 'isoCountryCode': 'LV',
    'languageId': '0',
    'regionName': 'Latvia',
    'regionTLD': '.lv',
    'regionid': '122'},
  { 'isoCountryCode': 'PM',
    'languageId': '0',
    'regionName': 'Saint Pierre and Miquelon',
    'regionTLD': '.pm',
    'regionid': '191'},
  { 'isoCountryCode': 'GN',
    'languageId': '0',
    'regionName': 'Guinea',
    'regionTLD': '.gn',
    'regionid': '92'},
  { 'isoCountryCode': 'RU',
    'languageId': '16',
    'regionName': 'Russian Federation',
    'regionTLD': '.ru',
    'regionid': '184'},
  { 'isoCountryCode': 'GW',
    'languageId': '0',
    'regionName': 'Guinea-Bissau',
    'regionTLD': '.gw',
    'regionid': '93'},
  { 'isoCountryCode': 'VN',
    'languageId': '0',
    'regionName': 'Viet Nam',
    'regionTLD': '.vn',
    'regionid': '241'},
  { 'isoCountryCode': 'SD',
    'languageId': '0',
    'regionName': 'Sudan',
    'regionTLD': '.sd',
    'regionid': '210'},
  { 'isoCountryCode': 'PE',
    'languageId': '0',
    'regionName': 'Peru',
    'regionTLD': '.pe',
    'regionid': '174'},
  { 'isoCountryCode': 'BH',
    'languageId': '0',
    'regionName': 'Bahrain',
    'regionTLD': '.bh',
    'regionid': '19'},
  { 'isoCountryCode': 'TO',
    'languageId': '0',
    'regionName': 'Tonga',
    'regionTLD': '.to',
    'regionid': '223'},
  { 'isoCountryCode': 'AZ',
    'languageId': '0',
    'regionName': 'Azerbaijan',
    'regionTLD': '.az',
    'regionid': '17'},
  { 'isoCountryCode': 'TT',
    'languageId': '0',
    'regionName': 'Trinidad and Tobago',
    'regionTLD': '.tt',
    'regionid': '224'},
  { 'isoCountryCode': 'LB',
    'languageId': '0',
    'regionName': 'Lebanon',
    'regionTLD': '.lb',
    'regionid': '123'},
  { 'isoCountryCode': 'QA',
    'languageId': '0',
    'regionName': 'Qatar',
    'regionTLD': '.qa',
    'regionid': '181'},
  { 'isoCountryCode': 'YE',
    'languageId': '0',
    'regionName': 'Yemen',
    'regionTLD': '.ye',
    'regionid': '246'},
  { 'isoCountryCode': 'NO',
    'languageId': '12',
    'regionName': 'Norway',
    'regionTLD': '.no',
    'regionid': '166'},
  { 'isoCountryCode': 'VE',
    'languageId': '0',
    'regionName': 'Venezuela',
    'regionTLD': '.ve',
    'regionid': '240'},
  { 'isoCountryCode': 'SB',
    'languageId': '0',
    'regionName': 'Solomon Islands',
    'regionTLD': '.sb',
    'regionid': '204'},
  { 'isoCountryCode': 'DM',
    'languageId': '0',
    'regionName': 'Dominica',
    'regionTLD': '.dm',
    'regionid': '62'},
  { 'isoCountryCode': 'CI',
    'languageId': '0',
    'regionName': "Cote d'Ivoire",
    'regionTLD': '.ci',
    'regionid': '55'},
  { 'isoCountryCode': 'GT',
    'languageId': '0',
    'regionName': 'Guatemala',
    'regionTLD': '.gt',
    'regionid': '90'},
  { 'isoCountryCode': 'SV',
    'languageId': '0',
    'regionName': 'El Salvador',
    'regionTLD': '.sv',
    'regionid': '66'},
  { 'isoCountryCode': 'DJ',
    'languageId': '0',
    'regionName': 'Djibouti',
    'regionTLD': '.dj',
    'regionid': '61'},
  { 'isoCountryCode': 'KI',
    'languageId': '0',
    'regionName': 'Kiribati',
    'regionTLD': '.ki',
    'regionid': '116'},
  { 'isoCountryCode': 'NI',
    'languageId': '0',
    'regionName': 'Nicaragua',
    'regionTLD': '.ni',
    'regionid': '160'},
  { 'isoCountryCode': 'SH',
    'languageId': '0',
    'regionName': 'Saint Helena',
    'regionTLD': '.sh',
    'regionid': '187'},
  { 'isoCountryCode': 'KN',
    'languageId': '0',
    'regionName': 'Saint Kitts and Nevis',
    'regionTLD': '.kn',
    'regionid': '188'},
  { 'isoCountryCode': 'GY',
    'languageId': '0',
    'regionName': 'Guyana',
    'regionTLD': '.gy',
    'regionid': '94'},
  { 'isoCountryCode': 'LI',
    'languageId': '0',
    'regionName': 'Liechtenstein',
    'regionTLD': '.li',
    'regionid': '127'},
  { 'isoCountryCode': 'PY',
    'languageId': '0',
    'regionName': 'Paraguay',
    'regionTLD': '.py',
    'regionid': '173'},
  { 'isoCountryCode': 'UM',
    'languageId': '0',
    'regionName': 'United States Minor Outlying Islands',
    'regionTLD': '.um',
    'regionid': '236'},
  { 'isoCountryCode': 'MO',
    'languageId': '0',
    'regionName': 'Macao',
    'regionTLD': '.mo',
    'regionid': '130'},
  { 'isoCountryCode': 'FI',
    'languageId': '8',
    'regionName': 'Finland',
    'regionTLD': '.fi',
    'regionid': '74'},
  { 'isoCountryCode': 'AM',
    'languageId': '0',
    'regionName': 'Armenia',
    'regionTLD': '.am-ignore',
    'regionid': '12'},
  { 'isoCountryCode': 'JE',
    'languageId': '0',
    'regionName': 'Jersey',
    'regionTLD': '.je',
    'regionid': '112'},
  { 'isoCountryCode': 'GG',
    'languageId': '0',
    'regionName': 'Guernsey',
    'regionTLD': '.gg',
    'regionid': '91'},
  { 'isoCountryCode': 'SC',
    'languageId': '0',
    'regionName': 'Seychelles',
    'regionTLD': '.sc',
    'regionid': '199'},
  { 'isoCountryCode': 'TR',
    'languageId': '14',
    'regionName': 'Turkey',
    'regionTLD': '.tr',
    'regionid': '226'},
  { 'isoCountryCode': 'IE',
    'languageId': '0',
    'regionName': 'Ireland',
    'regionTLD': '.ie',
    'regionid': '106'},
  { 'isoCountryCode': 'CV',
    'languageId': '0',
    'regionName': 'Cape Verde',
    'regionTLD': '.cv',
    'regionid': '41'},
  { 'isoCountryCode': 'LS',
    'languageId': '0',
    'regionName': 'Lesotho',
    'regionTLD': '.ls',
    'regionid': '124'},
  { 'isoCountryCode': 'BO',
    'languageId': '0',
    'regionName': 'Bolivia',
    'regionTLD': '.bo',
    'regionid': '28'},
  { 'isoCountryCode': 'CY',
    'languageId': '0',
    'regionName': 'Cyprus',
    'regionTLD': '.cy',
    'regionid': '58'},
  { 'isoCountryCode': 'TZ',
    'languageId': '0',
    'regionName': 'Tanzania, United Republic of',
    'regionTLD': '.tz',
    'regionid': '218'},
  { 'isoCountryCode': 'MZ',
    'languageId': '0',
    'regionName': 'Mozambique',
    'regionTLD': '.mz',
    'regionid': '151'},
  { 'isoCountryCode': 'FR',
    'languageId': '2',
    'regionName': 'France',
    'regionTLD': '.fr',
    'regionid': '75'},
  { 'isoCountryCode': 'CR',
    'languageId': '0',
    'regionName': 'Costa Rica',
    'regionTLD': '.cr',
    'regionid': '54'},
  { 'isoCountryCode': 'BM',
    'languageId': '0',
    'regionName': 'Bermuda',
    'regionTLD': '.bm',
    'regionid': '26'},
  { 'isoCountryCode': 'MA',
    'languageId': '0',
    'regionName': 'Morocco',
    'regionTLD': '.ma',
    'regionid': '150'},
  { 'isoCountryCode': 'PW',
    'languageId': '0',
    'regionName': 'Palau',
    'regionTLD': '.pw',
    'regionid': '169'},
  { 'isoCountryCode': 'PT',
    'languageId': '0',
    'regionName': 'Portugal',
    'regionTLD': '.pt',
    'regionid': '178'},
  { 'isoCountryCode': 'ZM',
    'languageId': '0',
    'regionName': 'Zambia',
    'regionTLD': '.zm',
    'regionid': '247'},
  { 'isoCountryCode': 'SY',
    'languageId': '0',
    'regionName': 'Syrian Arab Republic',
    'regionTLD': '.sy',
    'regionid': '215'},
  { 'isoCountryCode': 'PG',
    'languageId': '0',
    'regionName': 'Papua New Guinea',
    'regionTLD': '.pg',
    'regionid': '172'},
  { 'isoCountryCode': 'IO',
    'languageId': '0',
    'regionName': 'British Indian Ocean Territory',
    'regionTLD': '.io',
    'regionid': '33'},
  { 'isoCountryCode': 'BN',
    'languageId': '0',
    'regionName': 'Brunei Darussalam',
    'regionTLD': '.bn',
    'regionid': '34'},
  { 'isoCountryCode': 'BV',
    'languageId': '0',
    'regionName': 'Bouvet Island',
    'regionTLD': '.bv',
    'regionid': '31'},
  { 'isoCountryCode': 'MS',
    'languageId': '0',
    'regionName': 'Montserrat',
    'regionTLD': '.ms',
    'regionid': '149'},
  { 'isoCountryCode': 'IN',
    'languageId': '0',
    'regionName': 'India',
    'regionTLD': '.in',
    'regionid': '102'},
  { 'isoCountryCode': 'MY',
    'languageId': '0',
    'regionName': 'Malaysia',
    'regionTLD': '.my',
    'regionid': '134'},
  { 'isoCountryCode': 'TK',
    'languageId': '0',
    'regionName': 'Tokelau',
    'regionTLD': '.tk',
    'regionid': '222'},
  { 'isoCountryCode': 'KE',
    'languageId': '0',
    'regionName': 'Kenya',
    'regionTLD': '.ke',
    'regionid': '115'},
  { 'isoCountryCode': 'NP',
    'languageId': '0',
    'regionName': 'Nepal',
    'regionTLD': '.np',
    'regionid': '155'},
  { 'isoCountryCode': 'SO',
    'languageId': '0',
    'regionName': 'Somalia',
    'regionTLD': '.so',
    'regionid': '205'},
  { 'isoCountryCode': 'CN',
    'languageId': '15',
    'regionName': 'China',
    'regionTLD': '.cn',
    'regionid': '46'},
  { 'isoCountryCode': 'TC',
    'languageId': '0',
    'regionName': 'Turks and Caicos Islands',
    'regionTLD': '.tc',
    'regionid': '228'},
  { 'isoCountryCode': 'IS',
    'languageId': '0',
    'regionName': 'Iceland',
    'regionTLD': '.is',
    'regionid': '101'},
  { 'isoCountryCode': 'KM',
    'languageId': '0',
    'regionName': 'Comoros',
    'regionTLD': '.km',
    'regionid': '50'},
  { 'isoCountryCode': 'HM',
    'languageId': '0',
    'regionName': 'Heard Island and McDonald Islands',
    'regionTLD': '.hm',
    'regionid': '96'},
  { 'isoCountryCode': 'RW',
    'languageId': '0',
    'regionName': 'Rwanda',
    'regionTLD': '.rw',
    'regionid': '185'},
  { 'isoCountryCode': 'FK',
    'languageId': '0',
    'regionName': 'Falkland Islands (Malvinas)',
    'regionTLD': '.fk',
    'regionid': '71'},
  { 'isoCountryCode': 'null',
    'languageId': '0',
    'regionName': 'Unknown',
    'regionTLD': '.unknown',
    'regionid': '249'},
  { 'isoCountryCode': 'CX',
    'languageId': '0',
    'regionName': 'Christmas Island',
    'regionTLD': '.cx',
    'regionid': '47'},
  { 'isoCountryCode': 'HN',
    'languageId': '0',
    'regionName': 'Honduras',
    'regionTLD': '.hn',
    'regionid': '98'},
  { 'isoCountryCode': 'NL',
    'languageId': '11',
    'regionName': 'Netherlands',
    'regionTLD': '.nl',
    'regionid': '156'},
  { 'isoCountryCode': 'TD',
    'languageId': '0',
    'regionName': 'Chad',
    'regionTLD': '.td',
    'regionid': '44'},
  { 'isoCountryCode': 'KH',
    'languageId': '0',
    'regionName': 'Cambodia',
    'regionTLD': '.kh',
    'regionid': '38'},
  { 'isoCountryCode': 'MV',
    'languageId': '0',
    'regionName': 'Maldives',
    'regionTLD': '.mv',
    'regionid': '135'},
  { 'isoCountryCode': 'MR',
    'languageId': '0',
    'regionName': 'Mauritania',
    'regionTLD': '.mr',
    'regionid': '140'},
  { 'isoCountryCode': 'TF',
    'languageId': '0',
    'regionName': 'French Southern Territories',
    'regionTLD': '.tf',
    'regionid': '78'},
  { 'isoCountryCode': 'PH',
    'languageId': '0',
    'regionName': 'Philippines',
    'regionTLD': '.ph',
    'regionid': '175'},
  { 'isoCountryCode': 'MD',
    'languageId': '0',
    'regionName': 'Moldova, Republic of',
    'regionTLD': '.md',
    'regionid': '145'},
  { 'isoCountryCode': 'GI',
    'languageId': '0',
    'regionName': 'Gibraltar',
    'regionTLD': '.gi',
    'regionid': '84'},
  { 'isoCountryCode': 'EC',
    'languageId': '0',
    'regionName': 'Ecuador',
    'regionTLD': '.ec',
    'regionid': '64'},
  { 'isoCountryCode': 'WF',
    'languageId': '0',
    'regionName': 'Wallis and Futuna',
    'regionTLD': '.wf',
    'regionid': '244'},
  { 'isoCountryCode': 'SL',
    'languageId': '0',
    'regionName': 'Sierra Leone',
    'regionTLD': '.sl',
    'regionid': '200'},
  { 'isoCountryCode': 'AW',
    'languageId': '0',
    'regionName': 'Aruba',
    'regionTLD': '.aw',
    'regionid': '13'},
  { 'isoCountryCode': 'BD',
    'languageId': '0',
    'regionName': 'Bangladesh',
    'regionTLD': '.bd',
    'regionid': '20'},
  { 'isoCountryCode': 'CA',
    'languageId': '0',
    'regionName': 'Canada',
    'regionTLD': '.ca',
    'regionid': '40'},
  { 'isoCountryCode': 'KP',
    'languageId': '0',
    'regionName': "Korea, Democratic People's Republic of",
    'regionTLD': '.kp',
    'regionid': '117'},
  { 'isoCountryCode': 'LA',
    'languageId': '0',
    'regionName': "Lao People's Democratic Republic",
    'regionTLD': '.la',
    'regionid': '121'},
  { 'isoCountryCode': 'TN',
    'languageId': '0',
    'regionName': 'Tunisia',
    'regionTLD': '.tn',
    'regionid': '225'},
  { 'isoCountryCode': 'UA',
    'languageId': '0',
    'regionName': 'Ukraine',
    'regionTLD': '.ua',
    'regionid': '231'},
  { 'isoCountryCode': 'PA',
    'languageId': '0',
    'regionName': 'Panama',
    'regionTLD': '.pa',
    'regionid': '171'},
  { 'isoCountryCode': 'BZ',
    'languageId': '0',
    'regionName': 'Belize',
    'regionTLD': '.bz',
    'regionid': '24'},
  { 'isoCountryCode': 'SZ',
    'languageId': '0',
    'regionName': 'Swaziland',
    'regionTLD': '.sz',
    'regionid': '212'},
  { 'isoCountryCode': 'SA',
    'languageId': '0',
    'regionName': 'Saudi Arabia',
    'regionTLD': '.sa',
    'regionid': '196'},
  { 'isoCountryCode': 'GH',
    'languageId': '0',
    'regionName': 'Ghana',
    'regionTLD': '.gh',
    'regionid': '83'},
  { 'isoCountryCode': 'GQ',
    'languageId': '0',
    'regionName': 'Equatorial Guinea',
    'regionTLD': '.gq',
    'regionid': '67'},
  { 'isoCountryCode': 'IL',
    'languageId': '0',
    'regionName': 'Israel',
    'regionTLD': '.il',
    'regionid': '108'},
  { 'isoCountryCode': 'MN',
    'languageId': '0',
    'regionName': 'Mongolia',
    'regionTLD': '.mn',
    'regionid': '147'},
  { 'isoCountryCode': 'PL',
    'languageId': '0',
    'regionName': 'Poland',
    'regionTLD': '.pl',
    'regionid': '177'},
  { 'isoCountryCode': 'AT',
    'languageId': '0',
    'regionName': 'Austria',
    'regionTLD': '.at',
    'regionid': '16'},
  { 'isoCountryCode': 'OM',
    'languageId': '0',
    'regionName': 'Oman',
    'regionTLD': '.om',
    'regionid': '167'},
  { 'isoCountryCode': 'BL',
    'languageId': '0',
    'regionName': 'Saint Barthelemy',
    'regionTLD': '.bl',
    'regionid': '186'},
  { 'isoCountryCode': 'SE',
    'languageId': '13',
    'regionName': 'Sweden',
    'regionTLD': '.se',
    'regionid': '213'},
  { 'isoCountryCode': 'JM',
    'languageId': '0',
    'regionName': 'Jamaica',
    'regionTLD': '.jm',
    'regionid': '110'},
  { 'isoCountryCode': 'MQ',
    'languageId': '0',
    'regionName': 'Martinique',
    'regionTLD': '.mq',
    'regionid': '139'},
  { 'isoCountryCode': 'MX',
    'languageId': '3',
    'regionName': 'Mexico',
    'regionTLD': '.mx',
    'regionid': '143'},
  { 'isoCountryCode': 'ET',
    'languageId': '0',
    'regionName': 'Ethiopia',
    'regionTLD': '.et',
    'regionid': '70'},
  { 'isoCountryCode': 'NE',
    'languageId': '0',
    'regionName': 'Niger',
    'regionTLD': '.ne',
    'regionid': '161'},
  { 'isoCountryCode': 'CM',
    'languageId': '0',
    'regionName': 'Cameroon',
    'regionTLD': '.cm',
    'regionid': '39'},
  { 'isoCountryCode': 'DO',
    'languageId': '0',
    'regionName': 'Dominican Republic',
    'regionTLD': '.do',
    'regionid': '63'},
  { 'isoCountryCode': 'TJ',
    'languageId': '0',
    'regionName': 'Tajikistan',
    'regionTLD': '.tj',
    'regionid': '217'},
  { 'isoCountryCode': 'CZ',
    'languageId': '0',
    'regionName': 'Czech Republic',
    'regionTLD': '.cz',
    'regionid': '59'},
  { 'isoCountryCode': 'SI',
    'languageId': '0',
    'regionName': 'Slovenia',
    'regionTLD': '.si',
    'regionid': '203'},
  { 'isoCountryCode': 'RO',
    'languageId': '0',
    'regionName': 'Romania',
    'regionTLD': '.ro',
    'regionid': '183'},
  { 'isoCountryCode': 'GF',
    'languageId': '0',
    'regionName': 'French Guiana',
    'regionTLD': '.gf',
    'regionid': '76'},
  { 'isoCountryCode': 'WS',
    'languageId': '0',
    'regionName': 'Samoa',
    'regionTLD': '.ws-ignore',
    'regionid': '193'},
  { 'isoCountryCode': 'CH',
    'languageId': '0',
    'regionName': 'Switzerland',
    'regionTLD': '.ch',
    'regionid': '214'},
  { 'isoCountryCode': 'BY',
    'languageId': '0',
    'regionName': 'Belarus',
    'regionTLD': '.by',
    'regionid': '22'},
  { 'isoCountryCode': 'CC',
    'languageId': '0',
    'regionName': 'Cocos (Keeling) Islands',
    'regionTLD': '.cc-ignore',
    'regionid': '48'},
  { 'isoCountryCode': 'MM',
    'languageId': '0',
    'regionName': 'Myanmar',
    'regionTLD': '.mm',
    'regionid': '152'},
  { 'isoCountryCode': 'AF',
    'languageId': '0',
    'regionName': 'Afghanistan',
    'regionTLD': '.af',
    'regionid': '1'},
  { 'isoCountryCode': 'FM',
    'languageId': '0',
    'regionName': 'Micronesia, Federated States of',
    'regionTLD': '.fm-ignore',
    'regionid': '144'},
  { 'isoCountryCode': 'AN',
    'languageId': '0',
    'regionName': 'Netherlands Antilles',
    'regionTLD': '.an',
    'regionid': '157'},
  { 'isoCountryCode': 'GP',
    'languageId': '0',
    'regionName': 'Guadeloupe',
    'regionTLD': '.gp',
    'regionid': '88'},
  { 'isoCountryCode': 'UZ',
    'languageId': '0',
    'regionName': 'Uzbekistan',
    'regionTLD': '.uz',
    'regionid': '238'},
  { 'isoCountryCode': 'GD',
    'languageId': '0',
    'regionName': 'Grenada',
    'regionTLD': '.gd',
    'regionid': '87'},
  { 'isoCountryCode': 'YT',
    'languageId': '0',
    'regionName': 'Mayotte',
    'regionTLD': '.yt',
    'regionid': '142'},
  { 'isoCountryCode': 'SR',
    'languageId': '0',
    'regionName': 'Suriname',
    'regionTLD': '.sr',
    'regionid': '211'},
  { 'isoCountryCode': 'ES',
    'languageId': '18',
    'regionName': 'Spain',
    'regionTLD': '.es',
    'regionid': '208'},
  { 'isoCountryCode': 'KW',
    'languageId': '0',
    'regionName': 'Kuwait',
    'regionTLD': '.kw',
    'regionid': '119'},
  { 'isoCountryCode': 'ML',
    'languageId': '0',
    'regionName': 'Mali',
    'regionTLD': '.ml',
    'regionid': '136'},
  { 'isoCountryCode': 'CL',
    'languageId': '0',
    'regionName': 'Chile',
    'regionTLD': '.cl',
    'regionid': '45'},
  { 'isoCountryCode': 'PR',
    'languageId': '0',
    'regionName': 'Puerto Rico',
    'regionTLD': '.pr',
    'regionid': '180'},
  { 'isoCountryCode': 'LU',
    'languageId': '0',
    'regionName': 'Luxembourg',
    'regionTLD': '.lu',
    'regionid': '129'},
  { 'isoCountryCode': 'TL',
    'languageId': '0',
    'regionName': 'Timor-Leste',
    'regionTLD': '.tl',
    'regionid': '220'},
  { 'isoCountryCode': 'SG',
    'languageId': '0',
    'regionName': 'Singapore',
    'regionTLD': '.sg',
    'regionid': '201'},
  { 'isoCountryCode': 'GS',
    'languageId': '0',
    'regionName': 'South Georgia and the South Sandwich Islands',
    'regionTLD': '.gs',
    'regionid': '207'},
  { 'isoCountryCode': 'IR',
    'languageId': '0',
    'regionName': 'Iran, Islamic Republic of',
    'regionTLD': '.ir',
    'regionid': '104'},
  { 'isoCountryCode': 'MU',
    'languageId': '0',
    'regionName': 'Mauritius',
    'regionTLD': '.mu',
    'regionid': '141'},
  { 'isoCountryCode': 'TW',
    'languageId': '0',
    'regionName': 'Taiwan',
    'regionTLD': '.tw',
    'regionid': '216'},
  { 'isoCountryCode': 'AR',
    'languageId': '0',
    'regionName': 'Argentina',
    'regionTLD': '.ar',
    'regionid': '11'},
  { 'isoCountryCode': 'AG',
    'languageId': '0',
    'regionName': 'Antigua and Barbuda',
    'regionTLD': '.ag',
    'regionid': '10'},
  { 'isoCountryCode': 'LR',
    'languageId': '0',
    'regionName': 'Liberia',
    'regionTLD': '.lr',
    'regionid': '125'},
  { 'isoCountryCode': 'NR',
    'languageId': '0',
    'regionName': 'Nauru',
    'regionTLD': '.nr',
    'regionid': '154'},
  { 'isoCountryCode': 'VU',
    'languageId': '0',
    'regionName': 'Vanuatu',
    'regionTLD': '.vu',
    'regionid': '239'},
  { 'isoCountryCode': 'GL',
    'languageId': '0',
    'regionName': 'Greenland',
    'regionTLD': '.gl',
    'regionid': '86'},
  { 'isoCountryCode': 'VG',
    'languageId': '0',
    'regionName': 'Virgin Islands, British',
    'regionTLD': '.vg',
    'regionid': '242'},
  { 'isoCountryCode': 'EE',
    'languageId': '7',
    'regionName': 'Estonia',
    'regionTLD': '.ee',
    'regionid': '69'},
  { 'isoCountryCode': 'NG',
    'languageId': '0',
    'regionName': 'Nigeria',
    'regionTLD': '.ng',
    'regionid': '162'},
  { 'isoCountryCode': 'LY',
    'languageId': '0',
    'regionName': 'Libyan Arab Jamahiriya',
    'regionTLD': '.ly',
    'regionid': '126'},
  { 'isoCountryCode': 'MT',
    'languageId': '0',
    'regionName': 'Malta',
    'regionTLD': '.mt',
    'regionid': '137'},
  { 'isoCountryCode': 'SN',
    'languageId': '0',
    'regionName': 'Senegal',
    'regionTLD': '.sn',
    'regionid': '197'},
  { 'isoCountryCode': 'BS',
    'languageId': '0',
    'regionName': 'Bahamas',
    'regionTLD': '.bs',
    'regionid': '18'},
  { 'isoCountryCode': 'UG',
    'languageId': '0',
    'regionName': 'Uganda',
    'regionTLD': '.ug',
    'regionid': '230'},
  { 'isoCountryCode': 'LT',
    'languageId': '0',
    'regionName': 'Lithuania',
    'regionTLD': '.lt',
    'regionid': '128'},
  { 'isoCountryCode': 'BW',
    'languageId': '0',
    'regionName': 'Botswana',
    'regionTLD': '.bw',
    'regionid': '30'},
  { 'isoCountryCode': 'IT',
    'languageId': '5',
    'regionName': 'Italy',
    'regionTLD': '.it',
    'regionid': '109'},
  { 'isoCountryCode': 'NC',
    'languageId': '0',
    'regionName': 'New Caledonia',
    'regionTLD': '.nc',
    'regionid': '158'},
  { 'isoCountryCode': 'ME',
    'languageId': '0',
    'regionName': 'Montenegro',
    'regionTLD': '.me',
    'regionid': '148'},
  { 'isoCountryCode': 'VC',
    'languageId': '0',
    'regionName': 'Saint Vincent and the Grenadines',
    'regionTLD': '.vc',
    'regionid': '192'},
  { 'isoCountryCode': 'KY',
    'languageId': '0',
    'regionName': 'Cayman Islands',
    'regionTLD': '.ky',
    'regionid': '42'},
  { 'isoCountryCode': 'LK',
    'languageId': '0',
    'regionName': 'Sri Lanka',
    'regionTLD': '.lk',
    'regionid': '209'},
  { 'isoCountryCode': 'BI',
    'languageId': '0',
    'regionName': 'Burundi',
    'regionTLD': '.bi',
    'regionid': '37'},
  { 'isoCountryCode': 'ID',
    'languageId': '0',
    'regionName': 'Indonesia',
    'regionTLD': '.id',
    'regionid': '103'},
  { 'isoCountryCode': 'FO',
    'languageId': '0',
    'regionName': 'Faroe Islands',
    'regionTLD': '.fo',
    'regionid': '72'},
  { 'isoCountryCode': 'CU',
    'languageId': '0',
    'regionName': 'Cuba',
    'regionTLD': '.cu',
    'regionid': '57'},
  { 'isoCountryCode': 'KG',
    'languageId': '0',
    'regionName': 'Kyrgyzstan',
    'regionTLD': '.kg',
    'regionid': '120'},
  { 'isoCountryCode': 'TP',
    'languageId': '0',
    'regionName': 'Portuguese Timor',
    'regionTLD': '.tp',
    'regionid': '179'},
  { 'isoCountryCode': 'JP',
    'languageId': '9',
    'regionName': 'Japan',
    'regionTLD': '.jp',
    'regionid': '111'},
  { 'isoCountryCode': 'MH',
    'languageId': '0',
    'regionName': 'Marshall Islands',
    'regionTLD': '.mh',
    'regionid': '138'},
  { 'isoCountryCode': 'ZA',
    'languageId': '0',
    'regionName': 'South Africa',
    'regionTLD': '.za',
    'regionid': '206'},
  { 'isoCountryCode': 'JO',
    'languageId': '0',
    'regionName': 'Jordan',
    'regionTLD': '.jo',
    'regionid': '113'},
  { 'isoCountryCode': 'PF',
    'languageId': '0',
    'regionName': 'French Polynesia',
    'regionTLD': '.pf',
    'regionid': '77'},
  { 'isoCountryCode': 'IQ',
    'languageId': '0',
    'regionName': 'Iraq',
    'regionTLD': '.iq',
    'regionid': '105'},
  { 'isoCountryCode': 'IM',
    'languageId': '0',
    'regionName': 'Isle of Man',
    'regionTLD': '.im',
    'regionid': '107'},
  { 'isoCountryCode': 'US',
    'languageId': '0',
    'regionName': 'United States',
    'regionTLD': '.us',
    'regionid': '235'},
  { 'isoCountryCode': 'ER',
    'languageId': '0',
    'regionName': 'Eritrea',
    'regionTLD': '.er',
    'regionid': '68'},
  { 'isoCountryCode': 'MP',
    'languageId': '0',
    'regionName': 'Northern Mariana Islands',
    'regionTLD': '.mp',
    'regionid': '165'},
  { 'isoCountryCode': 'MF',
    'languageId': '0',
    'regionName': 'Saint Martin (French part)',
    'regionTLD': '.mf',
    'regionid': '190'},
  { 'isoCountryCode': 'LC',
    'languageId': '0',
    'regionName': 'Saint Lucia',
    'regionTLD': '.lc',
    'regionid': '189'},
  { 'isoCountryCode': 'BT',
    'languageId': '0',
    'regionName': 'Bhutan',
    'regionTLD': '.bt',
    'regionid': '27'},
  { 'isoCountryCode': 'BG',
    'languageId': '0',
    'regionName': 'Bulgaria',
    'regionTLD': '.bg',
    'regionid': '35'},
  { 'isoCountryCode': 'UK',
    'languageId': '0',
    'regionName': 'United Kingdom',
    'regionTLD': '.uk',
    'regionid': '234'},
  { 'isoCountryCode': 'AC',
    'languageId': '0',
    'regionName': 'Ascension Island',
    'regionTLD': '.ac',
    'regionid': '14'},
  { 'isoCountryCode': 'DZ',
    'languageId': '0',
    'regionName': 'Algeria',
    'regionTLD': '.dz',
    'regionid': '4'},
  { 'isoCountryCode': 'UY',
    'languageId': '0',
    'regionName': 'Uruguay',
    'regionTLD': '.uy',
    'regionid': '237'},
  { 'isoCountryCode': 'CF',
    'languageId': '0',
    'regionName': 'Central African Republic',
    'regionTLD': '.cf',
    'regionid': '43'},
  { 'isoCountryCode': 'AL',
    'languageId': '0',
    'regionName': 'Albania',
    'regionTLD': '.al',
    'regionid': '3'},
  { 'isoCountryCode': 'CG',
    'languageId': '0',
    'regionName': 'Congo',
    'regionTLD': '.cg',
    'regionid': '51'},
  { 'isoCountryCode': 'NF',
    'languageId': '0',
    'regionName': 'Norfolk Island',
    'regionTLD': '.nf',
    'regionid': '164'},
  { 'isoCountryCode': 'BA',
    'languageId': '0',
    'regionName': 'Bosnia and Herzegovina',
    'regionTLD': '.ba',
    'regionid': '29'},
  { 'isoCountryCode': 'CO',
    'languageId': '0',
    'regionName': 'Colombia',
    'regionTLD': '.co',
    'regionid': '49'},
  { 'isoCountryCode': 'GM',
    'languageId': '0',
    'regionName': 'Gambia',
    'regionTLD': '.gm',
    'regionid': '80'},
  { 'isoCountryCode': 'NU',
    'languageId': '0',
    'regionName': 'Niue',
    'regionTLD': '.nu-ignore',
    'regionid': '163'},
  { 'isoCountryCode': 'SK',
    'languageId': '0',
    'regionName': 'Slovakia',
    'regionTLD': '.sk',
    'regionid': '202'},
  { 'isoCountryCode': 'GU',
    'languageId': '0',
    'regionName': 'Guam',
    'regionTLD': '.gu',
    'regionid': '89'},
  { 'isoCountryCode': 'ZW',
    'languageId': '0',
    'regionName': 'Zimbabwe',
    'regionTLD': '.zw',
    'regionid': '248'},
  { 'isoCountryCode': 'KZ',
    'languageId': '0',
    'regionName': 'Kazakhstan',
    'regionTLD': '.kz',
    'regionid': '114'},
  { 'isoCountryCode': 'TV',
    'languageId': '0',
    'regionName': 'Tuvalu',
    'regionTLD': '.tv-ignore',
    'regionid': '229'},
  { 'isoCountryCode': 'HK',
    'languageId': '0',
    'regionName': 'Hong Kong',
    'regionTLD': '.hk',
    'regionid': '99'},
  { 'isoCountryCode': 'EH',
    'languageId': '0',
    'regionName': 'Western Sahara',
    'regionTLD': '.eh',
    'regionid': '245'},
  { 'isoCountryCode': 'GA',
    'languageId': '0',
    'regionName': 'Gabon',
    'regionTLD': '.ga',
    'regionid': '79'},
  { 'isoCountryCode': 'AO',
    'languageId': '0',
    'regionName': 'Angola',
    'regionTLD': '.ao',
    'regionid': '7'},
  { 'isoCountryCode': 'AU',
    'languageId': '0',
    'regionName': 'Australia',
    'regionTLD': '.au',
    'regionid': '15'},
  { 'isoCountryCode': 'CK',
    'languageId': '0',
    'regionName': 'Cook Islands',
    'regionTLD': '.ck',
    'regionid': '53'},
  { 'isoCountryCode': 'VA',
    'languageId': '0',
    'regionName': 'Holy See (Vatican City State)',
    'regionTLD': '.va',
    'regionid': '97'},
  { 'isoCountryCode': 'GB',
    'languageId': '0',
    'regionName': 'Great Britain',
    'regionTLD': '.gb',
    'regionid': '233'},
  { 'isoCountryCode': 'RS',
    'languageId': '0',
    'regionName': 'Serbia',
    'regionTLD': '.rs',
    'regionid': '198'},
  { 'isoCountryCode': 'BR',
    'languageId': '17',
    'regionName': 'Brazil',
    'regionTLD': '.br',
    'regionid': '32'},
  { 'isoCountryCode': 'SM',
    'languageId': '0',
    'regionName': 'San Marino',
    'regionTLD': '.sm',
    'regionid': '194'},
  { 'isoCountryCode': 'FJ',
    'languageId': '0',
    'regionName': 'Fiji',
    'regionTLD': '.fj',
    'regionid': '73'},
  { 'isoCountryCode': 'BJ',
    'languageId': '0',
    'regionName': 'Benin',
    'regionTLD': '.bj',
    'regionid': '25'},
  { 'isoCountryCode': 'BF',
    'languageId': '0',
    'regionName': 'Burkina Faso',
    'regionTLD': '.bf',
    'regionid': '36'},
  { 'isoCountryCode': 'HR',
    'languageId': '0',
    'regionName': 'Croatia',
    'regionTLD': '.hr',
    'regionid': '56'},
  { 'isoCountryCode': 'BB',
    'languageId': '0',
    'regionName': 'Barbados',
    'regionTLD': '.bb',
    'regionid': '21'},
  { 'isoCountryCode': 'AI',
    'languageId': '0',
    'regionName': 'Anguilla',
    'regionTLD': '.ai',
    'regionid': '8'},
  { 'isoCountryCode': 'CD',
    'languageId': '0',
    'regionName': 'Congo, The Democratic Republic of the',
    'regionTLD': '.cd',
    'regionid': '52'},
  { 'isoCountryCode': 'MG',
    'languageId': '0',
    'regionName': 'Madagascar',
    'regionTLD': '.mg',
    'regionid': '132'},
  { 'isoCountryCode': 'VI',
    'languageId': '0',
    'regionName': 'Virgin Islands, U.S.',
    'regionTLD': '.vi',
    'regionid': '243'},
  { 'isoCountryCode': 'TG',
    'languageId': '0',
    'regionName': 'Togo',
    'regionTLD': '.tg',
    'regionid': '221'},
  { 'isoCountryCode': 'NZ',
    'languageId': '0',
    'regionName': 'New Zealand',
    'regionTLD': '.nz',
    'regionid': '159'},
  { 'isoCountryCode': 'BE',
    'languageId': '0',
    'regionName': 'Belgium',
    'regionTLD': '.be',
    'regionid': '23'},
  { 'isoCountryCode': 'AQ',
    'languageId': '0',
    'regionName': 'Antarctica',
    'regionTLD': '.aq',
    'regionid': '9'},
  { 'isoCountryCode': 'NA',
    'languageId': '0',
    'regionName': 'Namibia',
    'regionTLD': '.na',
    'regionid': '153'},
  { 'isoCountryCode': 'MW',
    'languageId': '0',
    'regionName': 'Malawi',
    'regionTLD': '.mw',
    'regionid': '133'},
  { 'isoCountryCode': 'TH',
    'languageId': '0',
    'regionName': 'Thailand',
    'regionTLD': '.th',
    'regionid': '219'},
  { 'isoCountryCode': 'KR',
    'languageId': '10',
    'regionName': 'Korea, Republic of',
    'regionTLD': '.kr',
    'regionid': '118'},
  { 'isoCountryCode': 'AD',
    'languageId': '0',
    'regionName': 'Andorra',
    'regionTLD': '.ad',
    'regionid': '6'},
  { 'isoCountryCode': 'AS',
    'languageId': '0',
    'regionName': 'American Samoa',
    'regionTLD': '.as',
    'regionid': '5'},
  { 'isoCountryCode': 'HU',
    'languageId': '0',
    'regionName': 'Hungary',
    'regionTLD': '.hu',
    'regionid': '100'},
  { 'isoCountryCode': 'TM',
    'languageId': '0',
    'regionName': 'Turkmenistan',
    'regionTLD': '.tm',
    'regionid': '227'},
  { 'isoCountryCode': 'MK',
    'languageId': '0',
    'regionName': 'Macedonia, The Former Yugoslav Republic of',
    'regionTLD': '.mk',
    'regionid': '131'},
  { 'isoCountryCode': 'ST',
    'languageId': '0',
    'regionName': 'Sao Tome and Principe',
    'regionTLD': '.st',
    'regionid': '195'},
  { 'isoCountryCode': 'DK',
    'languageId': '6',
    'regionName': 'Denmark',
    'regionTLD': '.dk',
    'regionid': '60'},
  { 'isoCountryCode': 'AX',
    'languageId': '0',
    'regionName': 'Aland Islands',
    'regionTLD': '.ax',
    'regionid': '2'},
  { 'isoCountryCode': 'PN',
    'languageId': '0',
    'regionName': 'Pitcairn',
    'regionTLD': '.pn',
    'regionid': '176'},
  { 'isoCountryCode': 'MC',
    'languageId': '0',
    'regionName': 'Monaco',
    'regionTLD': '.mc',
    'regionid': '146'},
  { 'isoCountryCode': 'GR',
    'languageId': '0',
    'regionName': 'Greece',
    'regionTLD': '.gr',
    'regionid': '85'},
  { 'isoCountryCode': 'PS',
    'languageId': '0',
    'regionName': 'Palestinian Territory, Occupied',
    'regionTLD': '.ps',
    'regionid': '170'},
  { 'isoCountryCode': 'EG',
    'languageId': '0',
    'regionName': 'Egypt',
    'regionTLD': '.eg',
    'regionid': '65'},
  { 'isoCountryCode': 'HT',
    'languageId': '0',
    'regionName': 'Haiti',
    'regionTLD': '.ht',
    'regionid': '95'},
  { 'isoCountryCode': 'PK',
    'languageId': '0',
    'regionName': 'Pakistan',
    'regionTLD': '.pk',
    'regionid': '168'},
  { 'isoCountryCode': 'GE',
    'languageId': '0',
    'regionName': 'Georgia',
    'regionTLD': '.ge',
    'regionid': '81'}]
